# Generated by Django 3.1.1 on 2020-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('space', models.IntegerField()),
                ('year', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('price_total', models.IntegerField()),
                ('price_meter', models.IntegerField()),
                ('advertiser', models.CharField(db_column='Advertiser', max_length=20)),
                ('floor_total', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('elevator', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('warehouse', models.IntegerField()),
                ('link', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'apartment',
                'managed': False,
            },
        ),
    ]
